//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TabItem2 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TabItem2() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Translations.TabItem2", typeof(TabItem2).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab Item 2.
        /// </summary>
        public static string ControlName {
            get {
                return ResourceManager.GetString("ControlName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance Hash Code: .
        /// </summary>
        public static string InstanceHashCode {
            get {
                return ResourceManager.GetString("InstanceHashCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option 1.
        /// </summary>
        public static string Option1 {
            get {
                return ResourceManager.GetString("Option1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option 2.
        /// </summary>
        public static string Option2 {
            get {
                return ResourceManager.GetString("Option2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter A.
        /// </summary>
        public static string ParameterA {
            get {
                return ResourceManager.GetString("ParameterA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter B.
        /// </summary>
        public static string ParameterB {
            get {
                return ResourceManager.GetString("ParameterB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter C.
        /// </summary>
        public static string ParameterC {
            get {
                return ResourceManager.GetString("ParameterC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID PHU.
        /// </summary>
        public static string PHUID {
            get {
                return ResourceManager.GetString("PHUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHU List.
        /// </summary>
        public static string PHUList {
            get {
                return ResourceManager.GetString("PHUList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show PHU&apos;s Tubes.
        /// </summary>
        public static string ShowPHUTubes {
            get {
                return ResourceManager.GetString("ShowPHUTubes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WCF Test.
        /// </summary>
        public static string WCFTest {
            get {
                return ResourceManager.GetString("WCFTest", resourceCulture);
            }
        }
    }
}
