//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WPFBaseFrameworkEntities : DbContext
    {
        public WPFBaseFrameworkEntities()
            : base("name=WPFBaseFrameworkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PHU> PHU { get; set; }
        public virtual DbSet<PHUTube> PHUTube { get; set; }
        public virtual DbSet<Status> Status { get; set; }
    
        public virtual ObjectResult<PhuManager> spSelectPhuManager(string pHUID, string status)
        {
            var pHUIDParameter = pHUID != null ?
                new ObjectParameter("PHUID", pHUID) :
                new ObjectParameter("PHUID", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PhuManager>("spSelectPhuManager", pHUIDParameter, statusParameter);
        }
    }
}
