//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    
    public partial class PhuManager
    {
        public string PHUID { get; set; }
        public string Status { get; set; }
        public decimal OD { get; set; }
        public decimal WT { get; set; }
        public decimal TotalLength { get; set; }
    }
}
